from collections.abc import Iterable
from enum import StrEnum

from pydantic import BaseModel, ConfigDict, field_validator

from squeeze_core.adapters.diagnostics import DiagnosticSeverity


class ResearchDiagnosticCode(StrEnum):
    RESEARCH_CASE_UNKNOWN = "RESEARCH_CASE_UNKNOWN"
    RESEARCH_CASE_DUPLICATE = "RESEARCH_CASE_DUPLICATE"
    RESEARCH_CASE_STATUS_INCOMPLETE = "RESEARCH_CASE_STATUS_INCOMPLETE"
    RESEARCH_CASE_DETECTION_TIME_UNKNOWN = "RESEARCH_CASE_DETECTION_TIME_UNKNOWN"
    RESEARCH_CASE_EVALUATION_MISSING = "RESEARCH_CASE_EVALUATION_MISSING"
    RESEARCH_CASE_OUTCOME_MISSING = "RESEARCH_CASE_OUTCOME_MISSING"
    RESEARCH_CASE_PLATFORM_STATUS_UNKNOWN = "RESEARCH_CASE_PLATFORM_STATUS_UNKNOWN"
    RESEARCH_CASE_IDENTITY_CONFLICT = "RESEARCH_CASE_IDENTITY_CONFLICT"
    RESEARCH_DETECTION_POLICY_UNSUPPORTED = "RESEARCH_DETECTION_POLICY_UNSUPPORTED"
    RESEARCH_DETECTION_REQUIRED_RULE_UNKNOWN = "RESEARCH_DETECTION_REQUIRED_RULE_UNKNOWN"
    RESEARCH_DETECTION_REQUIRED_RULE_FAILED = "RESEARCH_DETECTION_REQUIRED_RULE_FAILED"
    RESEARCH_DETECTION_REQUIRED_RULE_CONFLICTED = "RESEARCH_DETECTION_REQUIRED_RULE_CONFLICTED"
    RESEARCH_DETECTION_REQUIRED_RULE_INSUFFICIENT = "RESEARCH_DETECTION_REQUIRED_RULE_INSUFFICIENT"
    RESEARCH_DETECTION_UNEVALUABLE = "RESEARCH_DETECTION_UNEVALUABLE"
    RESEARCH_OUTCOME_POLICY_UNSUPPORTED = "RESEARCH_OUTCOME_POLICY_UNSUPPORTED"
    RESEARCH_OUTCOME_UNKNOWN = "RESEARCH_OUTCOME_UNKNOWN"
    RESEARCH_OUTCOME_INSUFFICIENT = "RESEARCH_OUTCOME_INSUFFICIENT"
    RESEARCH_OUTCOME_PARTIAL = "RESEARCH_OUTCOME_PARTIAL"
    RESEARCH_OUTCOME_MIXED = "RESEARCH_OUTCOME_MIXED"
    RESEARCH_BATCH_EMPTY = "RESEARCH_BATCH_EMPTY"
    RESEARCH_BATCH_PARTIAL = "RESEARCH_BATCH_PARTIAL"
    RESEARCH_BATCH_CASE_FAILED = "RESEARCH_BATCH_CASE_FAILED"
    RESEARCH_BATCH_CASE_SKIPPED = "RESEARCH_BATCH_CASE_SKIPPED"
    RESEARCH_BATCH_SMALL_SAMPLE = "RESEARCH_BATCH_SMALL_SAMPLE"
    RESEARCH_DATASET_EMPTY = "RESEARCH_DATASET_EMPTY"
    RESEARCH_DATASET_PARTIAL = "RESEARCH_DATASET_PARTIAL"
    RESEARCH_DATASET_SYNTHETIC_ONLY = "RESEARCH_DATASET_SYNTHETIC_ONLY"
    RESEARCH_DATASET_MIXED_PROVENANCE = "RESEARCH_DATASET_MIXED_PROVENANCE"
    RESEARCH_DATASET_PUBLIC_EXPORT_REDACTED = "RESEARCH_DATASET_PUBLIC_EXPORT_REDACTED"


class ResearchDiagnostic(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    code: ResearchDiagnosticCode
    severity: DiagnosticSeverity
    case_id: str | None = None
    rule_id: str | None = None
    field_id: str | None = None
    input_ids: tuple[str, ...] = ()

    @field_validator("input_ids")
    @classmethod
    def sort_input_ids(cls, value: tuple[str, ...]) -> tuple[str, ...]:
        return tuple(sorted(set(value)))


def sort_diagnostics(items: Iterable[ResearchDiagnostic]) -> tuple[ResearchDiagnostic, ...]:
    return tuple(sorted(items, key=lambda item: (
        item.code.value,
        item.case_id or "",
        item.rule_id or "",
        item.field_id or "",
        item.input_ids,
    )))


__all__ = ["ResearchDiagnostic", "ResearchDiagnosticCode", "sort_diagnostics"]
