from collections.abc import Iterable
from enum import StrEnum

from pydantic import BaseModel, ConfigDict

from squeeze_core.adapters.diagnostics import DiagnosticSeverity


class MetricDiagnosticCode(StrEnum):
    """Stable, machine-readable diagnostic codes emitted by squeeze_core.metrics.

    Only codes that at least one metrics/ code path can actually emit are defined here;
    codes named in planning documents for policies Phase 2A does not implement (e.g. a
    TIME_RANGE window type) are intentionally omitted rather than left as dead enum members.
    """

    METRIC_MISSING_SYMBOL = "METRIC_MISSING_SYMBOL"
    METRIC_MISSING_AS_OF = "METRIC_MISSING_AS_OF"
    METRIC_UNSUPPORTED_METRIC = "METRIC_UNSUPPORTED_METRIC"
    METRIC_UNSUPPORTED_VERSION = "METRIC_UNSUPPORTED_VERSION"
    METRIC_NO_ELIGIBLE_BARS = "METRIC_NO_ELIGIBLE_BARS"
    METRIC_AMBIGUOUS_PROVIDER = "METRIC_AMBIGUOUS_PROVIDER"
    METRIC_INCOMPATIBLE_INTERVAL = "METRIC_INCOMPATIBLE_INTERVAL"
    METRIC_INCOMPATIBLE_SESSION = "METRIC_INCOMPATIBLE_SESSION"
    METRIC_UNKNOWN_AVAILABILITY = "METRIC_UNKNOWN_AVAILABILITY"
    METRIC_CONFLICTED_INPUT = "METRIC_CONFLICTED_INPUT"
    METRIC_CANCELLED_INPUT = "METRIC_CANCELLED_INPUT"
    METRIC_PARTIAL_INPUT = "METRIC_PARTIAL_INPUT"
    METRIC_INSUFFICIENT_HISTORY = "METRIC_INSUFFICIENT_HISTORY"
    METRIC_ZERO_DENOMINATOR = "METRIC_ZERO_DENOMINATOR"
    METRIC_MISSING_START_PRICE = "METRIC_MISSING_START_PRICE"
    METRIC_MISSING_END_PRICE = "METRIC_MISSING_END_PRICE"
    METRIC_MISSING_HIGH = "METRIC_MISSING_HIGH"
    METRIC_MISSING_LOW = "METRIC_MISSING_LOW"
    METRIC_MISSING_VOLUME = "METRIC_MISSING_VOLUME"
    METRIC_ZERO_VOLUME_SAMPLE = "METRIC_ZERO_VOLUME_SAMPLE"
    METRIC_EXCLUDED_CURRENT_BAR = "METRIC_EXCLUDED_CURRENT_BAR"

    RETURN_START_BAR_NOT_FOUND = "RETURN_START_BAR_NOT_FOUND"
    RETURN_END_BAR_NOT_FOUND = "RETURN_END_BAR_NOT_FOUND"
    RETURN_PRICE_FIELD_UNAVAILABLE = "RETURN_PRICE_FIELD_UNAVAILABLE"
    RETURN_IDENTICAL_INPUT_BAR = "RETURN_IDENTICAL_INPUT_BAR"

    GAP_PRIOR_SESSION_NOT_FOUND = "GAP_PRIOR_SESSION_NOT_FOUND"
    GAP_CURRENT_SESSION_NOT_FOUND = "GAP_CURRENT_SESSION_NOT_FOUND"
    GAP_PRIOR_CLOSE_UNAVAILABLE = "GAP_PRIOR_CLOSE_UNAVAILABLE"
    GAP_CURRENT_OPEN_UNAVAILABLE = "GAP_CURRENT_OPEN_UNAVAILABLE"
    GAP_SESSION_DATE_MISMATCH = "GAP_SESSION_DATE_MISMATCH"
    GAP_NONADJACENT_SESSION_POLICY = "GAP_NONADJACENT_SESSION_POLICY"

    RANGE_PARTIAL_BAR_UNSUPPORTED = "RANGE_PARTIAL_BAR_UNSUPPORTED"
    RANGE_ZERO_DENOMINATOR = "RANGE_ZERO_DENOMINATOR"

    VOLUME_BASELINE_WINDOW_EMPTY = "VOLUME_BASELINE_WINDOW_EMPTY"
    VOLUME_BASELINE_INSUFFICIENT_SAMPLES = "VOLUME_BASELINE_INSUFFICIENT_SAMPLES"
    VOLUME_BASELINE_MIXED_UNITS = "VOLUME_BASELINE_MIXED_UNITS"
    VOLUME_BASELINE_CURRENT_BAR_EXCLUDED = "VOLUME_BASELINE_CURRENT_BAR_EXCLUDED"

    # Phase 2B: normalized market-activity metrics (docs/phase-2b-design.md Section 16).
    # Additive only -- every code above is unchanged in value and meaning.
    NORMALIZED_METRIC_ZERO_BASELINE = "NORMALIZED_METRIC_ZERO_BASELINE"
    NORMALIZED_METRIC_ZERO_VARIANCE = "NORMALIZED_METRIC_ZERO_VARIANCE"
    NORMALIZED_METRIC_INSUFFICIENT_HISTORY = "NORMALIZED_METRIC_INSUFFICIENT_HISTORY"

    RELATIVE_VOLUME_TARGET_NOT_FOUND = "RELATIVE_VOLUME_TARGET_NOT_FOUND"
    RELATIVE_VOLUME_TARGET_MISSING_VOLUME = "RELATIVE_VOLUME_TARGET_MISSING_VOLUME"
    RELATIVE_VOLUME_BASELINE_UNAVAILABLE = "RELATIVE_VOLUME_BASELINE_UNAVAILABLE"
    RELATIVE_VOLUME_BASELINE_ZERO = "RELATIVE_VOLUME_BASELINE_ZERO"

    VOLUME_DISTRIBUTION_WINDOW_EMPTY = "VOLUME_DISTRIBUTION_WINDOW_EMPTY"
    VOLUME_DISTRIBUTION_INSUFFICIENT_SAMPLES = "VOLUME_DISTRIBUTION_INSUFFICIENT_SAMPLES"
    VOLUME_DISTRIBUTION_ZERO_VARIANCE = "VOLUME_DISTRIBUTION_ZERO_VARIANCE"

    RETURN_DISTRIBUTION_WINDOW_EMPTY = "RETURN_DISTRIBUTION_WINDOW_EMPTY"
    RETURN_DISTRIBUTION_INSUFFICIENT_BARS = "RETURN_DISTRIBUTION_INSUFFICIENT_BARS"
    RETURN_DISTRIBUTION_INSUFFICIENT_RETURNS = "RETURN_DISTRIBUTION_INSUFFICIENT_RETURNS"
    RETURN_DISTRIBUTION_ZERO_VARIANCE = "RETURN_DISTRIBUTION_ZERO_VARIANCE"
    RETURN_TARGET_NOT_FOUND = "RETURN_TARGET_NOT_FOUND"
    RETURN_TARGET_EXCLUDED_FROM_BASELINE = "RETURN_TARGET_EXCLUDED_FROM_BASELINE"

    # Phase 2C: short-interest and borrow-pressure metrics (docs/phase-2c-design.md Section 13).
    # Additive only -- every code above is unchanged in value and meaning.
    PRESSURE_METRIC_NO_ELIGIBLE_INPUT = "PRESSURE_METRIC_NO_ELIGIBLE_INPUT"
    PRESSURE_METRIC_AMBIGUOUS_PROVIDER = "PRESSURE_METRIC_AMBIGUOUS_PROVIDER"
    PRESSURE_METRIC_CONFLICTED_INPUT = "PRESSURE_METRIC_CONFLICTED_INPUT"
    PRESSURE_METRIC_START_AFTER_END = "PRESSURE_METRIC_START_AFTER_END"
    PRESSURE_METRIC_IDENTICAL_INPUT = "PRESSURE_METRIC_IDENTICAL_INPUT"

    SHORT_INTEREST_START_NOT_FOUND = "SHORT_INTEREST_START_NOT_FOUND"
    SHORT_INTEREST_END_NOT_FOUND = "SHORT_INTEREST_END_NOT_FOUND"
    SHORT_INTEREST_MISSING_VALUE = "SHORT_INTEREST_MISSING_VALUE"
    SHORT_INTEREST_ZERO_START_DENOMINATOR = "SHORT_INTEREST_ZERO_START_DENOMINATOR"
    SHORT_INTEREST_CANCELLED_INPUT = "SHORT_INTEREST_CANCELLED_INPUT"
    SHORT_INTEREST_REVISION_NOT_FOUND = "SHORT_INTEREST_REVISION_NOT_FOUND"
    SHORT_INTEREST_REVISION_LINK_MISSING = "SHORT_INTEREST_REVISION_LINK_MISSING"

    DAYS_TO_COVER_SHORT_INTEREST_NOT_FOUND = "DAYS_TO_COVER_SHORT_INTEREST_NOT_FOUND"
    DAYS_TO_COVER_VOLUME_BASELINE_UNAVAILABLE = "DAYS_TO_COVER_VOLUME_BASELINE_UNAVAILABLE"
    DAYS_TO_COVER_ZERO_VOLUME_BASELINE = "DAYS_TO_COVER_ZERO_VOLUME_BASELINE"
    DAYS_TO_COVER_INCOMPATIBLE_VOLUME_INTERVAL = "DAYS_TO_COVER_INCOMPATIBLE_VOLUME_INTERVAL"

    BORROW_FEE_START_NOT_FOUND = "BORROW_FEE_START_NOT_FOUND"
    BORROW_FEE_END_NOT_FOUND = "BORROW_FEE_END_NOT_FOUND"
    BORROW_FEE_MISSING_VALUE = "BORROW_FEE_MISSING_VALUE"
    BORROW_FEE_ZERO_START_DENOMINATOR = "BORROW_FEE_ZERO_START_DENOMINATOR"

    BORROW_AVAILABILITY_START_NOT_FOUND = "BORROW_AVAILABILITY_START_NOT_FOUND"
    BORROW_AVAILABILITY_END_NOT_FOUND = "BORROW_AVAILABILITY_END_NOT_FOUND"
    BORROW_AVAILABILITY_MISSING_VALUE = "BORROW_AVAILABILITY_MISSING_VALUE"
    BORROW_AVAILABILITY_ZERO_START_DENOMINATOR = "BORROW_AVAILABILITY_ZERO_START_DENOMINATOR"


class MetricDiagnostic(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    code: MetricDiagnosticCode
    severity: DiagnosticSeverity
    message: str
    observation_ids: tuple[str, ...] = ()


def sort_diagnostics(items: Iterable[MetricDiagnostic]) -> tuple[MetricDiagnostic, ...]:
    return tuple(
        sorted(
            items,
            key=lambda item: (item.code.value, item.observation_ids, item.message),
        )
    )
