from enum import StrEnum


class Classification(StrEnum):
    PRIME = "PRIME"
    SUBPRIME = "SUBPRIME"
    WATCH = "WATCH"
    NOT_QUALIFIED = "NOT_QUALIFIED"
    UNEVALUABLE = "UNEVALUABLE"
    CONFLICTED = "CONFLICTED"
    REFERENCE_DEFINITION_INCOMPLETE = "REFERENCE_DEFINITION_INCOMPLETE"


class CoverageCategory(StrEnum):
    HIGH = "HIGH_COVERAGE"
    MODERATE = "MODERATE_COVERAGE"
    LOW = "LOW_COVERAGE"
    INSUFFICIENT = "INSUFFICIENT_EVIDENCE"
    CONFLICTED = "CONFLICTED"


EXPERIMENTAL_LABEL = (
    "EXPERIMENTAL RESEARCH CLASSIFICATION — NOT PREDICTIVE VALIDATION"
)
