from collections.abc import Iterable
from enum import StrEnum

from pydantic import BaseModel, ConfigDict

from squeeze_core.adapters.diagnostics import DiagnosticSeverity


class ReadinessDiagnosticCode(StrEnum):
    """Stable, machine-readable diagnostic codes emitted by squeeze_core.readiness.

    Only codes an actually-implemented code path can emit are defined here, matching
    the convention set by squeeze_core.metrics.diagnostics.MetricDiagnosticCode. Every
    code here describes a structural-contract fact (presence, age, conflict,
    missingness) -- none carries trading meaning."""

    READINESS_UNSUPPORTED_OPERATION = "READINESS_UNSUPPORTED_OPERATION"
    READINESS_UNSUPPORTED_POLICY_VERSION = "READINESS_UNSUPPORTED_POLICY_VERSION"
    READINESS_MISSING_SYMBOL = "READINESS_MISSING_SYMBOL"
    READINESS_MISSING_AS_OF = "READINESS_MISSING_AS_OF"
    READINESS_REQUIRED_DOMAIN_MISSING = "READINESS_REQUIRED_DOMAIN_MISSING"
    READINESS_REQUIRED_DOMAIN_UNAVAILABLE = "READINESS_REQUIRED_DOMAIN_UNAVAILABLE"
    READINESS_REQUIRED_DOMAIN_CONFLICTED = "READINESS_REQUIRED_DOMAIN_CONFLICTED"
    READINESS_REQUIRED_DOMAIN_CANCELLED = "READINESS_REQUIRED_DOMAIN_CANCELLED"
    READINESS_REQUIRED_DOMAIN_PARTIAL = "READINESS_REQUIRED_DOMAIN_PARTIAL"
    READINESS_REQUIRED_DOMAIN_UNKNOWN = "READINESS_REQUIRED_DOMAIN_UNKNOWN"
    READINESS_REQUIRED_METRIC_MISSING = "READINESS_REQUIRED_METRIC_MISSING"
    READINESS_REQUIRED_UNIT_INCOMPATIBLE = "READINESS_REQUIRED_UNIT_INCOMPATIBLE"
    READINESS_REQUIRED_SCOPE_INCOMPATIBLE = "READINESS_REQUIRED_SCOPE_INCOMPATIBLE"
    READINESS_INSUFFICIENT_HISTORY = "READINESS_INSUFFICIENT_HISTORY"
    READINESS_UNKNOWN_AVAILABILITY = "READINESS_UNKNOWN_AVAILABILITY"

    COVERAGE_DOMAIN_PRESENT = "COVERAGE_DOMAIN_PRESENT"
    COVERAGE_DOMAIN_MISSING = "COVERAGE_DOMAIN_MISSING"
    COVERAGE_DOMAIN_UNAVAILABLE = "COVERAGE_DOMAIN_UNAVAILABLE"
    COVERAGE_DOMAIN_CONFLICTED = "COVERAGE_DOMAIN_CONFLICTED"
    COVERAGE_DOMAIN_CANCELLED = "COVERAGE_DOMAIN_CANCELLED"
    COVERAGE_DOMAIN_PARTIAL = "COVERAGE_DOMAIN_PARTIAL"
    COVERAGE_DOMAIN_UNKNOWN = "COVERAGE_DOMAIN_UNKNOWN"

    AGE_ALIGNMENT_NO_COMPARABLE_DOMAINS = "AGE_ALIGNMENT_NO_COMPARABLE_DOMAINS"
    AGE_ALIGNMENT_SINGLE_DOMAIN_ONLY = "AGE_ALIGNMENT_SINGLE_DOMAIN_ONLY"
    AGE_ALIGNMENT_MISSING_EFFECTIVE_TIME = "AGE_ALIGNMENT_MISSING_EFFECTIVE_TIME"
    AGE_ALIGNMENT_REPORTING_PERIOD_NOT_APPLICABLE = (
        "AGE_ALIGNMENT_REPORTING_PERIOD_NOT_APPLICABLE"
    )

    CONFLICT_SUMMARY_NO_CONFLICTS = "CONFLICT_SUMMARY_NO_CONFLICTS"
    CONFLICT_SUMMARY_UNRESOLVED_CONFLICT = "CONFLICT_SUMMARY_UNRESOLVED_CONFLICT"

    MISSINGNESS_REQUIRED_DOMAIN = "MISSINGNESS_REQUIRED_DOMAIN"
    MISSINGNESS_REQUIRED_METRIC = "MISSINGNESS_REQUIRED_METRIC"
    MISSINGNESS_INSUFFICIENT_HISTORY = "MISSINGNESS_INSUFFICIENT_HISTORY"
    MISSINGNESS_UNKNOWN_AVAILABILITY = "MISSINGNESS_UNKNOWN_AVAILABILITY"


class ReadinessDiagnostic(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    code: ReadinessDiagnosticCode
    severity: DiagnosticSeverity
    message: str
    domain: str | None = None
    observation_ids: tuple[str, ...] = ()


def sort_diagnostics(items: Iterable[ReadinessDiagnostic]) -> tuple[ReadinessDiagnostic, ...]:
    return tuple(
        sorted(
            items,
            key=lambda item: (item.code.value, item.domain or "", item.observation_ids, item.message),
        )
    )
