from collections.abc import Iterable
from enum import StrEnum

from pydantic import BaseModel, ConfigDict, field_validator

from squeeze_core.adapters.diagnostics import DiagnosticSeverity


class AnalysisDiagnosticCode(StrEnum):
    ANALYSIS_COHORT_EMPTY = "ANALYSIS_COHORT_EMPTY"
    ANALYSIS_COHORT_PARTIAL = "ANALYSIS_COHORT_PARTIAL"
    ANALYSIS_COHORT_SYNTHETIC_ONLY = "ANALYSIS_COHORT_SYNTHETIC_ONLY"
    ANALYSIS_COHORT_MIXED_PROVENANCE = "ANALYSIS_COHORT_MIXED_PROVENANCE"
    ANALYSIS_COHORT_EXCLUDED_INCOMPLETE_CASE = "ANALYSIS_COHORT_EXCLUDED_INCOMPLETE_CASE"
    ANALYSIS_COHORT_EXCLUDED_BLOCKED_CASE = "ANALYSIS_COHORT_EXCLUDED_BLOCKED_CASE"
    ANALYSIS_COHORT_EXCLUDED_OUTCOME_UNKNOWN = "ANALYSIS_COHORT_EXCLUDED_OUTCOME_UNKNOWN"
    ANALYSIS_COHORT_EXCLUDED_SYNTHETIC_CASE = "ANALYSIS_COHORT_EXCLUDED_SYNTHETIC_CASE"
    ANALYSIS_COHORT_EXCLUDED_DUPLICATE_SYMBOL_BOUNDARY = (
        "ANALYSIS_COHORT_EXCLUDED_DUPLICATE_SYMBOL_BOUNDARY"
    )
    ANALYSIS_REPEATED_SYMBOL_DETECTED = "ANALYSIS_REPEATED_SYMBOL_DETECTED"
    ANALYSIS_CASES_NOT_INDEPENDENT = "ANALYSIS_CASES_NOT_INDEPENDENT"
    ANALYSIS_BOUNDARY_SELECTION_APPLIED = "ANALYSIS_BOUNDARY_SELECTION_APPLIED"
    ANALYSIS_BOUNDARY_SELECTION_AMBIGUOUS = "ANALYSIS_BOUNDARY_SELECTION_AMBIGUOUS"
    ANALYSIS_RATE_UNDEFINED_ZERO_DENOMINATOR = "ANALYSIS_RATE_UNDEFINED_ZERO_DENOMINATOR"
    ANALYSIS_RATE_VERY_SMALL_SAMPLE = "ANALYSIS_RATE_VERY_SMALL_SAMPLE"
    ANALYSIS_RATE_DEPENDENCE_WARNING = "ANALYSIS_RATE_DEPENDENCE_WARNING"
    ANALYSIS_INTERVAL_NOT_COMPUTED = "ANALYSIS_INTERVAL_NOT_COMPUTED"
    ANALYSIS_INTERVAL_INDEPENDENCE_ASSUMPTION_UNSATISFIED = (
        "ANALYSIS_INTERVAL_INDEPENDENCE_ASSUMPTION_UNSATISFIED"
    )
    ANALYSIS_MISSING_SHORT_PRESSURE_EVIDENCE = "ANALYSIS_MISSING_SHORT_PRESSURE_EVIDENCE"
    ANALYSIS_MISSING_MOMENTUM_HISTORY = "ANALYSIS_MISSING_MOMENTUM_HISTORY"
    ANALYSIS_PARTIAL_OUTCOME_WINDOW = "ANALYSIS_PARTIAL_OUTCOME_WINDOW"
    ANALYSIS_PLATFORM_STATUS_UNKNOWN = "ANALYSIS_PLATFORM_STATUS_UNKNOWN"
    ANALYSIS_IDENTITY_CONFLICT = "ANALYSIS_IDENTITY_CONFLICT"
    ANALYSIS_INSUFFICIENT_HISTORICAL_CASES = "ANALYSIS_INSUFFICIENT_HISTORICAL_CASES"
    ANALYSIS_DESCRIPTIVE_ONLY = "ANALYSIS_DESCRIPTIVE_ONLY"
    ANALYSIS_NO_PREDICTIVE_VALIDATION = "ANALYSIS_NO_PREDICTIVE_VALIDATION"
    ANALYSIS_NO_CAUSAL_INFERENCE = "ANALYSIS_NO_CAUSAL_INFERENCE"
    ANALYSIS_SYNTHETIC_CASES_EXCLUDED_FROM_EMPIRICAL_RESULTS = (
        "ANALYSIS_SYNTHETIC_CASES_EXCLUDED_FROM_EMPIRICAL_RESULTS"
    )
    ANALYSIS_THRESHOLD_OPTIMIZATION_NOT_PERFORMED = (
        "ANALYSIS_THRESHOLD_OPTIMIZATION_NOT_PERFORMED"
    )


class AnalysisDiagnostic(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    code: AnalysisDiagnosticCode
    severity: DiagnosticSeverity
    cohort_id: str | None = None
    case_id: str | None = None
    symbol: str | None = None
    rule_id: str | None = None
    domain_id: str | None = None
    metric_name: str | None = None
    input_ids: tuple[str, ...] = ()

    @field_validator("input_ids")
    @classmethod
    def sort_input_ids(cls, value: tuple[str, ...]) -> tuple[str, ...]:
        return tuple(sorted(set(value)))


def sort_analysis_diagnostics(
    items: Iterable[AnalysisDiagnostic],
) -> tuple[AnalysisDiagnostic, ...]:
    return tuple(sorted(items, key=lambda item: (
        item.code.value,
        item.cohort_id or "",
        item.case_id or "",
        item.symbol or "",
        item.rule_id or "",
        item.domain_id or "",
        item.metric_name or "",
        item.input_ids,
    )))


__all__ = ["AnalysisDiagnostic", "AnalysisDiagnosticCode", "sort_analysis_diagnostics"]
