from enum import StrEnum


class PercentageUnit(StrEnum):
    PERCENT_POINTS = "PERCENT_POINTS"
    DECIMAL_FRACTION = "DECIMAL_FRACTION"
    FORMATTED_PERCENT_STRING = "FORMATTED_PERCENT_STRING"


class DateOnlyPublicationPolicy(StrEnum):
    STRICT_REJECT = "STRICT_REJECT"
    END_OF_PUBLICATION_DATE = "END_OF_PUBLICATION_DATE"
    INGESTION_TIME_UNCERTAIN_PLACEHOLDER = "INGESTION_TIME_UNCERTAIN_PLACEHOLDER"


class RevisionStatus(StrEnum):
    ORIGINAL = "ORIGINAL"
    CORRECTED = "CORRECTED"
    REVISED = "REVISED"
    CANCELLED = "CANCELLED"
    UNKNOWN = "UNKNOWN"


PROVIDER_SOURCE = "finra-shaped-published-short-interest"
